import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { PrimeReactProvider, PrimeReactContext } from 'primereact/api';
import styles from "./estilo.module.css";

import "primereact/resources/themes/lara-light-cyan/theme.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
              <PrimeReactProvider>

      <body
        className={`${geistSans.variable} ${geistMono.variable} background ${styles.background}`}
      >
        <main>
        {children}
        </main>
      </body>
      </PrimeReactProvider>
    </html>
  );
}
